from __future__ import annotations

from enum import StrEnum


class ProjectLifecycle(StrEnum):
    QUEUED = "QUEUED"
    ACTIVE = "ACTIVE"
    WAITING_HUMAN = "WAITING_HUMAN"
    PAUSED = "PAUSED"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class ProjectPhase(StrEnum):
    IDEATION = "IDEATION"
    EXPERIMENT = "EXPERIMENT"
    WRITING = "WRITING"
    TERMINAL = "TERMINAL"


class ProjectStage(StrEnum):
    LITERATURE_REVIEW = "LITERATURE_REVIEW"
    IDEA_GENERATION = "IDEA_GENERATION"
    IDEA_REVIEW = "IDEA_REVIEW"
    PROPOSAL_DRAFT = "PROPOSAL_DRAFT"
    PROPOSAL_REVIEW = "PROPOSAL_REVIEW"
    PROPOSAL_HUMAN_GATE = "PROPOSAL_HUMAN_GATE"
    EXPERIMENT_CONTRACT = "EXPERIMENT_CONTRACT"
    TOY_IMPLEMENT = "TOY_IMPLEMENT"
    TOY_RUN = "TOY_RUN"
    TOY_GATE = "TOY_GATE"
    FULL_IMPLEMENT = "FULL_IMPLEMENT"
    SMOKE_TEST = "SMOKE_TEST"
    REMOTE_RUN = "REMOTE_RUN"
    RESULT_VALIDATION = "RESULT_VALIDATION"
    EFFECTIVENESS_GATE = "EFFECTIVENESS_GATE"
    ANALYSIS_EXPERIMENTS = "ANALYSIS_EXPERIMENTS"
    EVIDENCE_BLUEPRINT = "EVIDENCE_BLUEPRINT"
    PAPER_DRAFT = "PAPER_DRAFT"
    EVIDENCE_AUDIT = "EVIDENCE_AUDIT"
    PAPER_REVIEW = "PAPER_REVIEW"
    PAPER_REVISION = "PAPER_REVISION"
    FINAL_HUMAN_GATE = "FINAL_HUMAN_GATE"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class TaskKind(StrEnum):
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    COMPUTE = "COMPUTE"
    HUMAN = "HUMAN"
    GATE = "GATE"


class TaskExecutor(StrEnum):
    CONTROLLER = "CONTROLLER"
    CODEX = "CODEX"
    HERMES = "HERMES"
    COMPUTE = "COMPUTE"
    HUMAN = "HUMAN"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class AgentRunStatus(StrEnum):
    QUEUED = "QUEUED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"


class ComputeExecutionStatus(StrEnum):
    CREATED = "CREATED"
    SUBMITTED = "SUBMITTED"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COLLECTING = "COLLECTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    OOM = "OOM"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"


class ObservationStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    UNREACHABLE = "UNREACHABLE"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    POLL_ERROR = "POLL_ERROR"


class ArtifactIntegrityStatus(StrEnum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    INVALID = "INVALID"


class FailureClass(StrEnum):
    NONE = "NONE"
    CODE = "CODE"
    ENVIRONMENT = "ENVIRONMENT"
    RESOURCE = "RESOURCE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    USER_CANCEL = "USER_CANCEL"
    UNKNOWN = "UNKNOWN"


class HealthLevel(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"


class AccessStatus(StrEnum):
    REACHABLE = "REACHABLE"
    UNREACHABLE = "UNREACHABLE"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    UNKNOWN = "UNKNOWN"


class ResourceState(StrEnum):
    UP = "UP"
    DEGRADED = "DEGRADED"
    DOWN = "DOWN"
    DRAINING = "DRAINING"
    UNKNOWN = "UNKNOWN"


class AccessMode(StrEnum):
    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
